/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controller.AdminController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.AccountType;
import models.TransactionType;

/**
 *
 * @author alexg
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        headingBanner = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnAddAccountType = new javax.swing.JButton();
        btnEditAccountType = new javax.swing.JButton();
        btnDeleteAccountType = new javax.swing.JButton();
        btnAddTransactionType = new javax.swing.JButton();
        btnEditTransactionType = new javax.swing.JButton();
        btnDeleteTransactionType = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BackPanel.setBackground(new java.awt.Color(0, 0, 0));
        BackPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/5cb0068c7da75a8e715438a94790626b.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/letter-x_1995355.jpg"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        headingBanner.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        headingBanner.setForeground(new java.awt.Color(240, 240, 240));
        headingBanner.setText("ADMIN DASHBOARD");
        headingBanner.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                headingBannerComponentAdded(evt);
            }
        });
        headingBanner.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                headingBannerAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account Type ID", "Name", "Description", "Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Display Account Types");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        btnAddAccountType.setText("Add Account Type");
        btnAddAccountType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddAccountTypeMouseClicked(evt);
            }
        });

        btnEditAccountType.setText("Edit Account Type");
        btnEditAccountType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditAccountTypeMouseClicked(evt);
            }
        });

        btnDeleteAccountType.setText("Delete Account Type");
        btnDeleteAccountType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteAccountTypeMouseClicked(evt);
            }
        });

        btnAddTransactionType.setText("Add Transaction Type");
        btnAddTransactionType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddTransactionTypeMouseClicked(evt);
            }
        });

        btnEditTransactionType.setText("Edit Transaction Type");
        btnEditTransactionType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditTransactionTypeMouseClicked(evt);
            }
        });

        btnDeleteTransactionType.setText("Delete Transaction Type");
        btnDeleteTransactionType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteTransactionTypeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BackPanelLayout = new javax.swing.GroupLayout(BackPanel);
        BackPanel.setLayout(BackPanelLayout);
        BackPanelLayout.setHorizontalGroup(
            BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackPanelLayout.createSequentialGroup()
                .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(BackPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddAccountType)
                            .addComponent(jButton1)
                            .addComponent(btnEditAccountType)
                            .addComponent(btnDeleteAccountType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BackPanelLayout.createSequentialGroup()
                            .addComponent(headingBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58)
                            .addComponent(jLabel3))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackPanelLayout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(22, 22, 22)))
                    .addGroup(BackPanelLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddTransactionType)
                            .addComponent(btnEditTransactionType)
                            .addComponent(btnDeleteTransactionType))))
                .addGap(278, 278, 278))
        );
        BackPanelLayout.setVerticalGroup(
            BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackPanelLayout.createSequentialGroup()
                .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(BackPanelLayout.createSequentialGroup()
                        .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(headingBanner))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackPanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddAccountType)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditAccountType)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteAccountType))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackPanelLayout.createSequentialGroup()
                        .addComponent(btnAddTransactionType)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditTransactionType)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteTransactionType)))
                .addGap(254, 254, 254))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void headingBannerComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_headingBannerComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_headingBannerComponentAdded

    private void headingBannerAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_headingBannerAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_headingBannerAncestorAdded

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        ArrayList accountTypeList = AdminController.getAccountTypes();
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        String[] stringArray = accountTypeList.toArray(new String[1]);
        for (int i = 0; i <= accountTypeList.size(); i++) {
            String tbData[] = (String[]) accountTypeList.get(i);
            tblModel.addRow(tbData);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnAddAccountTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddAccountTypeMouseClicked
        String name = JOptionPane.showInputDialog(null, "Enter Name Of Account Type");
        String description = JOptionPane.showInputDialog(null, "Enter Description Of Account Type");
        String code = JOptionPane.showInputDialog(null, "Enter Code Of Account Type");

        AccountType newType = new AccountType(name, description, code);
        AdminController.createNewAccountType(newType);

    }//GEN-LAST:event_btnAddAccountTypeMouseClicked

    private void btnEditAccountTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditAccountTypeMouseClicked
        // TODO add your handling code here:
        String code = JOptionPane.showInputDialog(null, "Enter Code Of The Account Type You Would Like To Change");
        String name = JOptionPane.showInputDialog(null, "Enter The New Name Of The Account Type");
        String description = JOptionPane.showInputDialog(null, "Enter The New Description Of The Account Type");

        AccountType changeType = new AccountType(name, description, code);
        AdminController.changeAccountType(changeType);
    }//GEN-LAST:event_btnEditAccountTypeMouseClicked

    private void btnDeleteAccountTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteAccountTypeMouseClicked
        // TODO add your handling code here:
        String code = JOptionPane.showInputDialog(null, "Enter Code Of The Account Type You Would Like To Delete");

        AdminController.deleteAccountType(code);
    }//GEN-LAST:event_btnDeleteAccountTypeMouseClicked

    private void btnAddTransactionTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddTransactionTypeMouseClicked
        String name = JOptionPane.showInputDialog(null, "Enter Name Of Transaction Type");
        String description = JOptionPane.showInputDialog(null, "Enter Description Of Transaction Type");
        String code = JOptionPane.showInputDialog(null, "Enter Code Of Transaction Type");

        TransactionType newType = new TransactionType(name, description, code);
        AdminController.createNewTransactionType(newType);
    }//GEN-LAST:event_btnAddTransactionTypeMouseClicked

    private void btnEditTransactionTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditTransactionTypeMouseClicked
        String code = JOptionPane.showInputDialog(null, "Enter Code Of The Transaction Type You Would Like To Change");
        String name = JOptionPane.showInputDialog(null, "Enter The New Name Of The Transaction Type");
        String description = JOptionPane.showInputDialog(null, "Enter The New Description Of The Transaction Type");

        TransactionType newType = new TransactionType(name, description, code);
        AdminController.changeTransactionType(newType);
    }//GEN-LAST:event_btnEditTransactionTypeMouseClicked

    private void btnDeleteTransactionTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteTransactionTypeMouseClicked
        String code = JOptionPane.showInputDialog(null, "Enter Code Of The Transaction Type You Would Like To Delete");

        AdminController.deleteTransactionType(code);
    }//GEN-LAST:event_btnDeleteTransactionTypeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackPanel;
    private javax.swing.JButton btnAddAccountType;
    private javax.swing.JButton btnAddTransactionType;
    private javax.swing.JButton btnDeleteAccountType;
    private javax.swing.JButton btnDeleteTransactionType;
    private javax.swing.JButton btnEditAccountType;
    private javax.swing.JButton btnEditTransactionType;
    private javax.swing.JLabel headingBanner;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
